name: Feature Request 🚀
description: Create a new feature request
title: '[Feature]: '
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        If you have any new ideas for features or improvements, please note all relevant requirements for your feature.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the requirements for your feature?
      placeholder: Describe your feature here.
      value: 'I need a new feature to perform X.'
    validations:
      required: true
  - type: checkboxes
    id: area-of-focus
    attributes:
      label: Area of Focus
      description: What are the area of focus that this feature encompasses?
      options:
        - label: Frontend
        - label: Backend
        - label: DevOps
    validations:
      required: true
